In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
%cd /content/gdrive/MyDrive/imageclassification

/content/gdrive/MyDrive/imageclassification


In [3]:
%cd image_retrieval/

/content/gdrive/MyDrive/imageclassification/image_retrieval


***Lấy file query ***

In [4]:
import os
def get_file_query():
  path= "gt_files/"
  list_gt = os.listdir(path)
  list_files_query=[]
  for file_name in list_gt:
    name=file_name.split(".")[0].split("_")[-1]
    if(name=="query"):
      list_files_query.append(file_name)
  return list_files_query


In [5]:
list_files_query= get_file_query()
print(list_files_query)
print(len(list_files_query))

['all_souls_4_query.txt', 'all_souls_1_query.txt', 'all_souls_2_query.txt', 'bodleian_2_query.txt', 'balliol_4_query.txt', 'balliol_5_query.txt', 'bodleian_1_query.txt', 'ashmolean_3_query.txt', 'ashmolean_1_query.txt', 'ashmolean_2_query.txt', 'all_souls_5_query.txt', 'bodleian_3_query.txt', 'ashmolean_5_query.txt', 'balliol_2_query.txt', 'ashmolean_4_query.txt', 'balliol_3_query.txt', 'balliol_1_query.txt', 'christ_church_3_query.txt', 'cornmarket_1_query.txt', 'christ_church_1_query.txt', 'christ_church_4_query.txt', 'bodleian_5_query.txt', 'cornmarket_5_query.txt', 'cornmarket_4_query.txt', 'cornmarket_2_query.txt', 'hertford_1_query.txt', 'bodleian_4_query.txt', 'cornmarket_3_query.txt', 'christ_church_5_query.txt', 'christ_church_2_query.txt', 'magdalen_5_query.txt', 'keble_2_query.txt', 'magdalen_1_query.txt', 'hertford_2_query.txt', 'magdalen_2_query.txt', 'keble_1_query.txt', 'hertford_3_query.txt', 'magdalen_3_query.txt', 'hertford_5_query.txt', 'hertford_4_query.txt', 'keble

**lấy file ảnh tương ứng với querry (gồm 3 file good, oke, junk)**

In [6]:
#get file good,oke,junk correspond
def get_file_name(list_files_query, name):
  list_files_name=[]
  for query_file in list_files_query:
    name_correspond= query_file.replace("query",name)
    list_files_name.append(name_correspond)
  return list_files_name
  



In [7]:
list_files_good=get_file_name(list_files_query,"good")
list_files_junk=get_file_name(list_files_query,"junk")
list_files_ok=get_file_name(list_files_query,"ok")
# print(len(list_files_ok))
# print(list_files_ok)

**lấy ảnh trong file query**

In [8]:
def get_image_query(list_files_query):
  list_image_query=[]
  for query in list_files_query:
    dir= "/content/gdrive/MyDrive/imageclassification/image_retrieval/gt_files/"+query
    with open(dir,"r") as f:
      for line in f.readlines():
        name_image= line.split(" ")[0].split("_",1)[1]
        list_image_query.append(name_image)
  return list_image_query

In [9]:
test=get_image_query(list_files_query)
print(test)

['all_souls_000051', 'all_souls_000013', 'all_souls_000026', 'oxford_002416', 'balliol_000194', 'oxford_001753', 'bodleian_000107', 'ashmolean_000269', 'ashmolean_000058', 'ashmolean_000000', 'oxford_003410', 'bodleian_000108', 'ashmolean_000305', 'balliol_000187', 'ashmolean_000007', 'balliol_000167', 'balliol_000051', 'christ_church_000999', 'cornmarket_000047', 'christ_church_000179', 'christ_church_001020', 'bodleian_000163', 'cornmarket_000131', 'oxford_000545', 'cornmarket_000105', 'hertford_000015', 'bodleian_000407', 'cornmarket_000019', 'oxford_002562', 'oxford_002734', 'magdalen_000560', 'keble_000214', 'magdalen_000078', 'oxford_001752', 'oxford_003335', 'keble_000245', 'oxford_000317', 'magdalen_000058', 'hertford_000063', 'hertford_000027', 'keble_000055', 'keble_000227', 'keble_000028', 'oxford_001115', 'pitt_rivers_000119', 'radcliffe_camera_000095', 'oxford_002904', 'pitt_rivers_000033', 'radcliffe_camera_000523', 'pitt_rivers_000153', 'pitt_rivers_000087', 'radcliffe_c

**lấy ảnh tương ứng của query với từng file good, oke, junk**

In [10]:
def get_image_correspond(file_name):
  list_image_name= []
  with open("gt_files/"+file_name,"r") as f:
    for line in f.readlines():
      list_image_name.append(line.split("\n")[0]+".jpg")
  return list_image_name

In [11]:
test=get_image_correspond(list_files_good[0])
print(test)

['all_souls_000091.jpg', 'all_souls_000026.jpg', 'oxford_003410.jpg', 'oxford_002985.jpg', 'all_souls_000015.jpg', 'oxford_000926.jpg', 'all_souls_000055.jpg', 'oxford_001955.jpg', 'all_souls_000140.jpg', 'all_souls_000068.jpg', 'all_souls_000002.jpg', 'all_souls_000006.jpg', 'all_souls_000209.jpg', 'all_souls_000146.jpg', 'oxford_001264.jpg', 'all_souls_000013.jpg', 'oxford_000669.jpg', 'oxford_002503.jpg', 'oxford_002338.jpg', 'oxford_000962.jpg', 'all_souls_000040.jpg', 'all_souls_000150.jpg', 'oxford_001308.jpg', 'oxford_001806.jpg']


In [12]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from PIL import Image

In [13]:
import keras
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input
from keras import Model, layers
from keras.preprocessing import image
from keras.models import load_model, model_from_json
import PIL
import os

In [14]:
conv_base = ResNet50(
    include_top=False,
    weights="imagenet")

for layer in conv_base.layers:
    layer.trainable = True

94781440/94765736 [==============================] - 4s 0us/step


In [ ]:
conv_base.summary()

Model: "resnet50"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, None, None,  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, None, None, 3 0           input_2[0][0]                    
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, None, None, 6 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, None, None, 6 256         conv1_conv[0][0]                 
___________________________________________________________________________________________

In [15]:
x = conv_base.output
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(128, activation='relu')(x) 
predictions = layers.Dense(11, activation='softmax')(x)
model = Model(conv_base.input, predictions)

**model lấy vector embedding**

In [16]:
model_new=model
layer_name = 'global_average_pooling2d'
intermediate_layer_model = Model(model.input,model_new.get_layer(layer_name).output)

In [17]:
print(list_files_query)
print(list_files_good)
print(list_files_junk)
print(list_files_ok)

['all_souls_4_query.txt', 'all_souls_1_query.txt', 'all_souls_2_query.txt', 'bodleian_2_query.txt', 'balliol_4_query.txt', 'balliol_5_query.txt', 'bodleian_1_query.txt', 'ashmolean_3_query.txt', 'ashmolean_1_query.txt', 'ashmolean_2_query.txt', 'all_souls_5_query.txt', 'bodleian_3_query.txt', 'ashmolean_5_query.txt', 'balliol_2_query.txt', 'ashmolean_4_query.txt', 'balliol_3_query.txt', 'balliol_1_query.txt', 'christ_church_3_query.txt', 'cornmarket_1_query.txt', 'christ_church_1_query.txt', 'christ_church_4_query.txt', 'bodleian_5_query.txt', 'cornmarket_5_query.txt', 'cornmarket_4_query.txt', 'cornmarket_2_query.txt', 'hertford_1_query.txt', 'bodleian_4_query.txt', 'cornmarket_3_query.txt', 'christ_church_5_query.txt', 'christ_church_2_query.txt', 'magdalen_5_query.txt', 'keble_2_query.txt', 'magdalen_1_query.txt', 'hertford_2_query.txt', 'magdalen_2_query.txt', 'keble_1_query.txt', 'hertford_3_query.txt', 'magdalen_3_query.txt', 'hertford_5_query.txt', 'hertford_4_query.txt', 'keble

*** ảnh trong file query***

In [18]:
im_list_query=get_image_query(list_files_query)
print(im_list_query)

['all_souls_000051', 'all_souls_000013', 'all_souls_000026', 'oxford_002416', 'balliol_000194', 'oxford_001753', 'bodleian_000107', 'ashmolean_000269', 'ashmolean_000058', 'ashmolean_000000', 'oxford_003410', 'bodleian_000108', 'ashmolean_000305', 'balliol_000187', 'ashmolean_000007', 'balliol_000167', 'balliol_000051', 'christ_church_000999', 'cornmarket_000047', 'christ_church_000179', 'christ_church_001020', 'bodleian_000163', 'cornmarket_000131', 'oxford_000545', 'cornmarket_000105', 'hertford_000015', 'bodleian_000407', 'cornmarket_000019', 'oxford_002562', 'oxford_002734', 'magdalen_000560', 'keble_000214', 'magdalen_000078', 'oxford_001752', 'oxford_003335', 'keble_000245', 'oxford_000317', 'magdalen_000058', 'hertford_000063', 'hertford_000027', 'keble_000055', 'keble_000227', 'keble_000028', 'oxford_001115', 'pitt_rivers_000119', 'radcliffe_camera_000095', 'oxford_002904', 'pitt_rivers_000033', 'radcliffe_camera_000523', 'pitt_rivers_000153', 'pitt_rivers_000087', 'radcliffe_c

In [19]:
img_list_query = [Image.open("oxbuild_images/" + img_path+".jpg") for img_path in im_list_query]

**lấy vector của 55 query**

In [20]:
query_batch = np.stack([preprocess_input(np.array(img.resize((224,224))))
                             for img in img_list_query])

In [21]:
vector_query = intermediate_layer_model.predict(query_batch)
print(vector_query)

[[0.02882949 0.07660425 0.58019674 ... 0.18384881 0.         0.        ]
 [0.13005437 0.2185377  0.         ... 0.         0.10029952 0.18391477]
 [0.         0.48042166 0.         ... 0.09130072 0.11395085 0.04332052]
 ...
 [0.17823958 1.1520598  0.12684478 ... 0.5281182  0.         0.5174135 ]
 [0.5431824  0.16699219 0.         ... 0.45380998 0.02218735 0.10812732]
 [0.2263202  0.4103369  0.         ... 0.5021833  0.01078204 0.27561134]]


In [32]:
# test_datagen = ImageDataGenerator(
#     preprocessing_function=preprocess_input)

# test_generator = test_datagen.flow_from_directory(
#     "/content/gdrive/MyDrive/imageclassification/Object Dataset/test",
#     batch_size=9,
#     shuffle=False,
#     target_size=(224,224))

Found 5063 images belonging to 1 classes.


In [22]:
# dataset= os.listdir("oxbuild_images/")

**ghi file dataset để tái sử dụng**


In [ ]:
# with open('datasets.txt', 'w') as f:
#     for item in dataset:
#         f.write("%s\n" % item)

**load dataset đã lưu**

In [ ]:
dataset= []
with open("datasets.txt","r") as f:
  for line in f.readlines():
    dataset.append(line.split("\n")[0])
dataset

In [24]:
len(dataset)

5063

**lấy vector embedding của datasets**

In [ ]:
# import os
# vector_dataset=[]
# for image in dataset:
#   img= Image.open("oxbuild_images/" + image)
#   batch = preprocess_input(np.array(img.resize((224,224)))) 
#   batch= np.expand_dims(batch,axis=0)
#   vector_image = intermediate_layer_model.predict(batch)
#   vector_dataset.append(vector_image[0])
# print(len(vector_dataset))
  

5063


In [ ]:
# vector_dataset=np.array(vector_dataset)
# vector_dataset.shape

(5063, 2048)

In [ ]:
# vector_dataset

array([[0.19183229, 0.27032402, 0.13711667, ..., 0.32060122, 0.2910028 ,
        0.05002087],
       [0.07601001, 0.53621906, 0.642616  , ..., 0.02023629, 0.15770663,
        0.        ],
       [0.86983484, 0.        , 0.741712  , ..., 1.1880835 , 0.2308159 ,
        0.12857588],
       ...,
       [0.09564415, 0.9626154 , 0.0725367 , ..., 0.6996335 , 0.26540753,
        0.3688213 ],
       [0.03156238, 1.4195745 , 0.05304163, ..., 1.6722535 , 0.4787585 ,
        0.6403248 ],
       [0.06274646, 0.01859887, 0.32638624, ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

lưu vecto embedding dataset

In [ ]:
import pickle
with open("embedding_datasets.pickle", 'wb') as f:
    pickle.dump(vector_dataset, f)

load vector embedding dataset

In [26]:
import pickle
with open("embedding_datasets.pickle", "rb") as f:
    vector_dataset = pickle.load(f)

In [27]:
vector_dataset

array([[0.19183229, 0.27032402, 0.13711667, ..., 0.32060122, 0.2910028 ,
        0.05002087],
       [0.07601001, 0.53621906, 0.642616  , ..., 0.02023629, 0.15770663,
        0.        ],
       [0.86983484, 0.        , 0.741712  , ..., 1.1880835 , 0.2308159 ,
        0.12857588],
       ...,
       [0.09564415, 0.9626154 , 0.0725367 , ..., 0.6996335 , 0.26540753,
        0.3688213 ],
       [0.03156238, 1.4195745 , 0.05304163, ..., 1.6722535 , 0.4787585 ,
        0.6403248 ],
       [0.06274646, 0.01859887, 0.32638624, ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [28]:
print(vector_query.shape)
print(vector_dataset.shape)

(55, 2048)
(5063, 2048)


tính giao của 2 array-> kết quả trả về theo thứ tự của array 1

In [29]:
def intersection(lst1, lst2):
    lst3 = [value for value in lst1 if value in lst2]
    return lst3

**tính map_good**

In [30]:
list_ap_good=[]
for i in range(len(list_files_query)):
  vector_l2_dataset=np.linalg.norm(vector_query[i]-vector_dataset,axis=-1)
  gt=get_image_correspond(list_files_good[i])
  toplen_image_query= np.argsort(vector_l2_dataset) 
  for i in range(len(vector_dataset)):
    all_image_in_top=toplen_image_query[:(len(gt)+i)]
    image_correspond= [dataset[image] for image in all_image_in_top]
    if(intersection(gt,image_correspond)==gt):
      break
  index=[]
  AP=0
  for j in range(len(image_correspond)):
    if(image_correspond[j] in gt):
      index.append(j)
  for k in range(len(index)):
    AP= AP+ ((k+1)/(index[k]+1))
  AP=AP/len(gt)
  list_ap_good.append(AP)
map_good=sum(list_ap_good)/len(list_ap_good)
print(list_ap_good)
print(map_good)

[0.05917014849775563, 0.07259949329825116, 0.2832230116956839, 0.37414824393209145, 0.5645431335002701, 0.11562028795174864, 0.6642680676270333, 0.040554461128633305, 0.5088444234711706, 0.5151066050948203, 0.45845388243285634, 0.6232474116723034, 0.36145905067456713, 0.0120787073862099, 0.4772153694014622, 0.046640845879783926, 0.5745918904686677, 0.6359028294022867, 0.6571942446043165, 0.7556615777735791, 0.19846346103869236, 0.55040099827015, 0.6720588235294118, 0.42860317460317454, 0.0884664839440025, 0.6161305233340322, 0.47473615676738884, 0.8027027027027026, 0.06773745608063939, 0.7315691164593423, 0.2035886533941772, 0.564711654589372, 0.28540729311481783, 0.6689000157310555, 0.06777997865724755, 0.48221963151344766, 0.60375340947423, 0.19790186738445795, 0.5356425500212351, 0.32731664769092245, 0.4660353535353536, 0.6769453664190506, 0.20930962037438774, 0.08068759390675911, 0.9166666666666666, 0.537499947364511, 0.5178065385292223, 1.0, 0.7926957557545167, 0.75, 0.36458333333